services:
  - type: web
    name: money-transfer-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/money-transfer-app-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_CACHE_TYPE
        value: simple 