spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: false
  
  cache:
    type: simple

# Application Configuration for Testing
app:
  transfer:
    max-amount: 1000000.00
    min-amount: 0.01
    lock-timeout: 10
    retry-attempts: 2
    concurrent-transfers-limit: 50

# Logging Configuration for Testing
logging:
  level:
    com.moneytransfer: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN 