spring:
  application:
    name: money-transfer-app
  
  datasource:
    url: jdbc:h2:mem:moneytransferdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: false
  
  cache:
    type: simple

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false

# Server Configuration
server:
  port: ${PORT:${SERVER_PORT:8080}}
  servlet:
    context-path: /

# Application Specific Configuration
app:
  transfer:
    max-amount: 1000000.00
    min-amount: 0.01
    lock-timeout: 30
    retry-attempts: 3
    concurrent-transfers-limit: 100

# Logging Configuration
logging:
  level:
    root: INFO
    com.moneytransfer: INFO
    org.springframework: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 